# -*- coding: utf-8 -*-
"""Minor Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WJQifj4g8Wm1Hbg7-XPHBzV_T1_mSjgO

ML MODEL

importing libraries
"""

import pandas as pd
import numpy as np
import datetime
import matplotlib
import matplotlib.pyplot as plt
import nltk

"""# LOADING THE DATASET"""

#loading the dataset
df = pd.read_csv("binary_with_artist.csv", low_memory=False)
#df = pd.read_csv("binary.csv", low_memory=False)
df.head()

df.columns

y=df.mood #mood of song
X=df.drop(['index', 'name ', 'mood', 'year', 'artist', 'lyrics'], axis=1)

#dividing the dataset into 80:20 ratio
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix

logistic_model = LogisticRegression(multi_class='multinomial', solver='lbfgs', max_iter=1000)
logistic_model.fit(X_train, y_train)

# Predict on the test data
y_pred_logistic = logistic_model.predict(X_test)

# Evaluate Logistic Regression model
print("Logistic Regression Results:")
print(f"Accuracy: {accuracy_score(y_test, y_pred_logistic)}")
print(classification_report(y_test, y_pred_logistic))
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_logistic))

# Step 2: Train Support Vector Machine (SVM) model
svm_model = SVC(kernel='linear')  # Linear kernel for simplicity
svm_model.fit(X_train, y_train)

# Predict on the test data
y_pred_svm = svm_model.predict(X_test)

# Evaluate SVM model
print("\nSVM Results:")
print(f"Accuracy: {accuracy_score(y_test, y_pred_svm)}")
print(classification_report(y_test, y_pred_svm))
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_svm))

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV
from sklearn.preprocessing import StandardScaler

# Define a parameter grid for Logistic Regression
param_grid = {
    'C': [0.001, 0.01, 0.1, 1, 10],
    'penalty': ['l1', 'l2'],
    'solver': ['liblinear', 'sag']  # Add 'sag' solver as an option
}

# Create a Logistic Regression classifier
lr_model = LogisticRegression(max_iter=1000)  # Increase max_iter

# Create a grid search object
grid_search = GridSearchCV(lr_model, param_grid, scoring='accuracy', cv=5)

# Scale the data (if necessary)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Train the model with grid search
grid_search.fit(X_train_scaled, y_train)

# Get the best model and its accuracy
best_model = grid_search.best_estimator_
best_accuracy = grid_search.best_score_

print(f"Best Logistic Regression Accuracy: {best_accuracy}")

# Use the best model for prediction on test data
y_pred_lr = best_model.predict(X_test_scaled)

# Evaluate the best Logistic Regression model
# ... (rest of your evaluation code)

# Save the models (optional)
import pickle
with open('logistic_model.pkl', 'wb') as f:
    pickle.dump(logistic_model, f)
with open('svm_model.pkl', 'wb') as f:
    pickle.dump(svm_model, f)

from sklearn.model_selection import cross_val_score

# Logistic Regression with Cross-Validation
logistic_model = LogisticRegression(multi_class='multinomial', solver='lbfgs', max_iter=1000, class_weight='balanced')
scores = cross_val_score(logistic_model, X, y, cv=5, scoring='accuracy')
print(f"Cross-Validation Accuracy for Logistic Regression: {scores.mean()}")

# SVM with Cross-Validation
svm_model = SVC(kernel='linear', class_weight='balanced')
scores_svm = cross_val_score(svm_model, X, y, cv=5, scoring='accuracy')
print(f"Cross-Validation Accuracy for SVM: {scores_svm.mean()}")

"""----"""

# Step 1: Install Required Libraries (Uncomment the line below if needed)
# !pip install matplotlib numpy

# Step 2: Import Libraries
import numpy as np
import matplotlib.pyplot as plt

# Step 3: Define Your Data
# Model Names
metrics = ['Accuracy', 'Precision', 'Recall', 'F1-Score']

# Metrics for each model
logistic_regression = [0.53, 0.55, 0.53, 0.52]  # Blue
svm = [0.49, 0.51, 0.49, 0.48]  # Red

# Setting the width of the bars
bar_width = 0.35  # Width for the bars

# Step 4: Set Positions of the Bar Groups
r1 = np.arange(len(metrics))  # Positions for Logistic Regression
r2 = [x + bar_width for x in r1]  # Positions for SVM

# Step 5: Create the Bar Graph
plt.figure(figsize=(10, 6))

# Create bars
plt.bar(r1, logistic_regression, color='skyblue', width=bar_width, edgecolor='grey', label='Logistic Regression')
plt.bar(r2, svm, color='salmon', width=bar_width, edgecolor='grey', label='SVM')

# Adding labels
plt.xlabel('Metrics', fontweight='bold')
plt.ylabel('Scores', fontweight='bold')
plt.title('Model Performance Metrics Comparison', fontweight='bold')

# Set x-ticks to show the metric names
plt.xticks([r + bar_width / 2 for r in range(len(metrics))], metrics)

# Set y-axis limits for better visibility
plt.ylim(0, 1)  # Set the y-axis range to 0-1

# Create legend & Show graphic
plt.legend()
plt.tight_layout()
plt.show()