# -*- coding: utf-8 -*-
"""Minor - preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19ikD5BFSD22WEih-2KeCyhd6FEW90KvV

26 Aug
"""

# Import packages
import pandas as pd
import numpy as np
import seaborn as sns
import re

import nltk
from nltk import FreqDist

# Load the CSV file
data_frame = pd.read_csv("telugusongs.csv", low_memory=False)
data_frame.set_index('index',inplace = True)
new_data_frame = data_frame
data_frame.head(5)

# Function to remove punctuation
def RemovePunctuation(my_str):
    no_punct = ""
    no_punct = re.sub('[!A-Z#?,)(.-:";]', '', my_str)
    return no_punct

# Remove punctuation from lyrics
my_str_series = data_frame['lyrics']
i = 1
for my_str in my_str_series:
    new_str = RemovePunctuation(my_str)
    new_data_frame.at[i, 'lyrics'] = new_str
    i = i + 1

# Print the updated dataframe
new_data_frame.head(5)

# Save the data without punctuation to a new CSV file
new_data_frame.to_csv('new_telugu.csv')

# Download the Punkt tokenizer models
nltk.download('punkt')

f = open("stopwords.txt", mode="r", encoding="utf-8")
wordlist = f.read()
f.close()

# Tokenize the stopwords
words = nltk.tokenize.word_tokenize(wordlist)
unique_word_list = list(set(words))

# Write unique stopwords back to file
f = open("telugu_stopwords.txt", mode="w", encoding="utf-8")
for ele in unique_word_list:
    f.write(ele + '\n')
f.close()

# Define a function to generate stem words
def generate_stem_words(word):
    suffixes = {
        1: [u"లు", u"లు", u"లో", u"ని", u"తో"],
        2: [u"లు", u"లు", u"వారు", u"గారు", u"మంది"],
        3: [u"చేసిన", u"ఉన్న", u"కోసం", u"ఎందుకు", u"విషయం"],
        4: [u"ఉంటుంది", u"పొందింది", u"పొందిన"],
        5: [u"ఉంటుంది", u"ఉంటారు", u"కొందరు"],
    }
    for L in 5, 4, 3, 2:
        if len(word) > L + 1:
            for suf in suffixes[L]:
                if word.endswith(suf):
                    return word[:-L]
    return word

# Stemming and removing stopwords from lyrics
newest_data_frame = new_data_frame.copy()

for ind in range(1, len(new_data_frame['lyrics'])):
    my_str_series = new_data_frame.loc[ind, 'lyrics']
    words_DF = nltk.tokenize.word_tokenize(my_str_series)
    str_without_stopwords = ""
    stem_word = ""
    for str_ in words_DF:
        if str_ not in unique_word_list:
            stem_word = generate_stem_words(str_)
            str_without_stopwords = str_without_stopwords + stem_word + " "
    newest_data_frame.at[ind, 'lyrics'] = str_without_stopwords

# Display the newest dataframe
newest_data_frame.head(5)

# Save the processed data to a new CSV file
newest_data_frame.to_csv('processed_telugu_songs.csv')

#classify stemmed data
import logging
import pandas as pd
import numpy as np
from numpy import random

import nltk
from sklearn.pipeline import Pipeline
from sklearn.metrics import classification_report

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer,TfidfTransformer

from sklearn.metrics import accuracy_score, confusion_matrix
import matplotlib.pyplot as plt
from nltk.corpus import stopwords
import re
y = newest_data_frame.mood
x=newest_data_frame.lyrics

X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2) # use random number generator
x

"""# **unigrams for lyrics**"""

#unigram dataframe
features=[]
newest_data_frame = new_data_frame
for ind in range(1,len(new_data_frame['lyrics'])):
    my_str_series = new_data_frame.loc[ind]['lyrics']
    words_DF = nltk.tokenize.word_tokenize(my_str_series)
    strwithoutstopwords = ""
    stem_word=""
    for str_ in words_DF:
        #print(str_)..

        #words_DF = nltk.tokenize.word_tokenize(str_)
        #for wrd in words_DF:
        if str_ not in unique_word_list:
            #stem_word=generate_stem_words(str_)
            strwithoutstopwords=strwithoutstopwords+str_+" "
            features.append(str_)
    #without_stopword_songs.append(strwithoutstopwords)
    newest_data_frame.set_value(ind,'lyrics',strwithoutstopwords)

def unique(list1):

    # intilize a null list
    unique_list = []

    # traverse for all elements .0000000000000000000000000000000000000000.....................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000.


    for x in list1:
        # check if exists in unique_list or not
        if x not in unique_list:
            unique_list.append(x)
    # print list
    return unique_list


features=unique(features)
val=[0]*len(newest_data_frame['lyrics'])
print(len(features))
for i in range(0,len(features)):
    newest_data_frame[features[i]]=val;
def val(feat):
    for ind in range(1,len(newest_data_frame['lyrics'])):
        temp = newest_data_frame.loc[ind]['lyrics']
        if feat in temp:
            newest_data_frame.set_value(ind,feat,1)
for i in range(0,len(features)):
    val(features[i])

newest_data_frame

import nltk

# Initialize empty feature list
features = []
newest_data_frame = new_data_frame

# Loop over the DataFrame
for ind in range(1, len(new_data_frame['lyrics'])):
    my_str_series = new_data_frame.loc[ind, 'lyrics']
    words_DF = nltk.tokenize.word_tokenize(my_str_series)
    strwithoutstopwords = ""

    for str_ in words_DF:
        # If word is not in unique_word_list, add it to strwithoutstopwords and features
        if str_ not in unique_word_list:
            strwithoutstopwords = strwithoutstopwords + str_ + " "
            features.append(str_)

    # Update the DataFrame using `at[]` instead of `set_value`
    newest_data_frame.at[ind, 'lyrics'] = strwithoutstopwords

# Function to get unique elements from a list
def unique(list1):
    unique_list = []
    for x in list1:
        if x not in unique_list:
            unique_list.append(x)
    return unique_list

# Get unique features
features = unique(features)

# Initialize a column of zeros for each feature
val = [0] * len(newest_data_frame['lyrics'])
for feature in features:
    newest_data_frame[feature] = val

# Function to update feature presence in the DataFrame
def val(feat):
    for ind in range(1, len(newest_data_frame['lyrics'])):
        temp = newest_data_frame.loc[ind, 'lyrics']
        if feat in temp:
            newest_data_frame.at[ind, feat] = 1

# Apply val function to all features
for feature in features:
    val(feature)

# Display the updated DataFrame
newest_data_frame

# Initialize empty lists to store features and corresponding values
features = []
newest_data_frame = new_data_frame.copy()

# Process each song's lyrics to remove stopwords and collect unigrams
for ind in range(1, len(new_data_frame['lyrics'])):
    my_str_series = new_data_frame.loc[ind]['lyrics']
    words_DF = nltk.tokenize.word_tokenize(my_str_series)
    strwithoutstopwords = ""

    for str_ in words_DF:
        if str_ not in unique_word_list:
            strwithoutstopwords += str_ + " "
            features.append(str_)

    newest_data_frame.at[ind, 'lyrics'] = strwithoutstopwords

# Remove duplicates from the feature list
features = list(set(features))

# Prepare a DataFrame to hold all new unigram columns
unigram_columns = pd.DataFrame(0, index=newest_data_frame.index, columns=features)

# Fill the unigram columns based on the presence of each feature in the lyrics
for ind in range(1, len(newest_data_frame['lyrics'])):
    temp = newest_data_frame.loc[ind, 'lyrics']
    for feat in features:
        if feat in temp:
            unigram_columns.at[ind, feat] = 1

# Concatenate the unigram columns with the original DataFrame
newest_data_frame = pd.concat([newest_data_frame, unigram_columns], axis=1)

# Display the resulting DataFrame
newest_data_frame.head()

"""# unigrams for artist"""

# Initialize empty lists to store features and corresponding values
features = []
newest_data_frame = new_data_frame.copy()

# Process each song's artist name to remove stopwords and collect unique features (artist names)
for ind in range(1, len(new_data_frame['artist'])):
    my_str_series = new_data_frame.loc[ind]['artist']
    words_DF = nltk.tokenize.word_tokenize(my_str_series)
    strwithoutstopwords = ""

    for str_ in words_DF:
        if str_ not in unique_word_list:
            strwithoutstopwords += str_ + " "
            features.append(str_)

    # Use .at[] instead of .set_value
    newest_data_frame.at[ind, 'artist'] = strwithoutstopwords

# Remove duplicates from the feature list
features = list(set(features))

# Prepare a DataFrame to hold all new feature columns
feature_columns = pd.DataFrame(0, index=newest_data_frame.index, columns=features)

# Fill the feature columns based on the presence of each feature in the artist names
for ind in range(1, len(newest_data_frame['artist'])):
    temp = newest_data_frame.loc[ind, 'artist']
    for feat in features:
        if feat in temp:
            feature_columns.at[ind, feat] = 1

# Concatenate the feature columns with the original DataFrame
newest_data_frame = pd.concat([newest_data_frame, feature_columns], axis=1)

# Display the resulting DataFrame
newest_data_frame.head()

newest_data_frame.to_csv('binary_with_artist.csv')

